import '@/styles/globals.css'

import { SpeedInsights } from '@vercel/speed-insights/next'
import { Provider } from '@/provider'

import { Toaster } from '@shadcn/ui/sonner'

import { Inter } from 'next/font/google'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
})

export const metadata = {
	title: 'mfas',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="ja">
			<body className={`font-sans ${inter.variable}`}>
				<Provider>{children}</Provider>
				<Toaster />
				<SpeedInsights />
			</body>
		</html>
	)
}
