import '@/styles/globals.css'

import { NextAuthProvider } from '@/provider/nextauth'
import { getServerAuthSession } from '@/server/auth'

import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/shadcn/theme/theme-provider'

import { TRPCReactProvider } from '@/trpc/react'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
})

export const metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const session = await getServerAuthSession()

	return (
		<html lang="ja">
			<body className={`font-sans ${inter.variable}`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<NextAuthProvider session={session}>
						<TRPCReactProvider>{children}</TRPCReactProvider>
					</NextAuthProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
